name: Build and test app
on:
  push:
    branches: [ master ] # action effectuée quand on push sur master
  pull_request:
    branches: [ master ] # action effectuée quand on fait une PR vers master

jobs: # list des jobs à effectuer
  build:
    runs-on: ubuntu-latest # On utilise une image ubuntu pour exécuter les jobs
    steps:
      - uses: actions/checkout@v2 # on fait un checkout du projet
      - name: Set up JDK 11 # on utilise Java 11
        uses: actions/setup-java@v2 # On configure Java
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Compiler le projet # On donne un nom au job
        run: mvn -B -X -DskipTests clean package # On lance la commande maven qui lance le build du code
      - name: Build the tests #
        run: mvn test
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: iuts3.class
          # Optional (recommended) mail server password:
          password: kvkekkddxgmibljv
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: loic.pantano@gmail.com
          # Required sender full name (address can be skipped):
          from: Luke Skywalker # <user@example.com>
      - name: Slack Notificationv
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: https://hooks.slack.com/services/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